site_name: Docs of Jian
site_description: A blogging site by Jian
site_url: http://blog.99092019.xyz

theme:
  name: material
  favicon: assets/logo.jpg
  logo: assets/logo.jpg
  font:
    text: "Microsoft Yahei"
    code: "Consolas,Courier,courier new,stkaiti,kaiti,simkai,monospace"
  custom_dir: overrides
  language: zh
  palette:
  # Dark Mode
  # - scheme: slate
  #   toggle:
  #     icon: material/weather-sunny
  #     name: 切换至日间模式
  #   primary: deep orange
  #   accent: deep purple

  # Light Mode
  - scheme: default
    # toggle:
    #   icon: material/weather-night
    #   name: 切换至夜间模式
    primary: deep purple
    accent: deep orange
  features:
    - content.code.copy      # 代码复制
    - content.code.annotate
    - navigation.top         # 返回顶部的按钮
    - navigation.instant
    - navigation.tracking    # 地址栏中URL将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs
    - navigation.indexes     # 启用节索引后，可以将文档直接附加到节
    - navigation.sections
    - navigation.path
    - navigation.footer
    - search.suggest         # 搜索输入一些字母时推荐补全整个单词
    - search.highlight       # 搜索出的文章关键词加入高亮
    - search.share           # 搜索分享

nav:
  - 主页: index.md 
  - 文稿: 
    - blog/index.md
  - 标签: tag.md
  - 时光: 
    - 轨迹: moment/moment.md
    - 烟台: moment/yantai.md
    - 大同: moment/datong.md
    - 武汉: moment/wuhan.md
    - 恩施: moment/enshi.md
  - 碎碎念:
    - 从0到1：开启商业与未来的秘密: read/zero_to_one.md
  - 关于: about.md

plugins:
  - search
  # - awesome-nav
  - blog:
      blog_dir: blog
      post_dir: "{blog}/posts"
      post_date_format: full
      post_url_format: "{slug}"
      pagination_per_page: 5
  - tags
  

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  analytics:
    provider: google
    property: G-EHVNYDZB7M

extra_css:
  - stylesheets/extra.css 
  
copyright: Copyright &copy; 2024 - 2026 Jian Zhang
repo_url: https://github.com/luck19990920/Docs_of_Jian.github.io/
repo_name: Docs_of_Jian
use_directory_urls: false