site_name: Docs of Jian
site_description: A blogging site by Jian
site_url: http://blog.99092019.xyz

theme:
  name: material
  font:
    text: "Microsoft Yahei"
    code: "Consolas,Courier,courier new,stkaiti,kaiti,simkai,monospace"
  custom_dir: overrides
  language: zh
  palette:
  # Dark Mode
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: 切换至日间模式
    primary: deep orange
    accent: deep purple

  # Light Mode
  - scheme: default
    toggle:
      icon: material/weather-night
      name: 切换至夜间模式
    primary: deep purple
    accent: deep orange
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.top

plugins:
  - search
  - blog:
      blog_dir: .
      post_url_format: "{slug}"
      pagination_per_page: 5
  - tags:
      tags_file: tags.md
  

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra:
  analytics:
    provider: google
    property: G-EHVNYDZB7M

copyright: Copyright &copy; 2024 - 2025 Jian Zhang
repo_url: https://github.com/luck19990920
repo_name: luck19990920.github
use_directory_urls: false